"""
Companies repository for managing company records.

Provides type-safe CRUD operations for the companies table with domain model integration.
"""

from datetime import UTC, datetime

from supabase import Client

from data.supebase.base_repository import BaseRepository
from data.supebase.exceptions import SupabaseNotFoundError
from data.supebase.models.company import Company


class CompaniesRepository(BaseRepository):
    """
    Repository for companies table operations.

    Provides methods to:
    - Create new companies
    - Retrieve active companies
    - Activate/deactivate companies (soft delete)

    All methods return type-safe Company domain models.
    """

    def __init__(self, client: Client) -> None:
        """
        Initialize companies repository.

        Args:
            client: Supabase client instance
        """
        super().__init__(client, "companies")

    def create(self, name: str, is_active: bool = True) -> Company:
        """
        Create a new company.

        Args:
            name: Company name (must be unique, validated by DB constraint)
            is_active: Whether the company should be active (default: True)

        Returns:
            Created Company instance with all fields populated

        Raises:
            SupabaseConflictError: If company name already exists
            SupabaseValidationError: If name violates database constraints
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = CompaniesRepository(client)
            company = repo.create(name="Acme Corp", is_active=True)
            print(company.id)  # Auto-generated ID
            print(company.is_active)  # True
            ```
        """
        # Insert record (timestamps auto-generated by DB)
        result = self.insert({"name": name, "is_active": is_active})

        # Handle response - insert returns list or single dict
        data = result[0] if isinstance(result, list) else result

        # Convert to domain model
        company = Company(**data)

        return company

    def get_active(self) -> list[Company]:
        """
        Get all active companies ordered by name.

        Returns:
            List of active Company instances (empty list if none exist)

        Raises:
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = CompaniesRepository(client)
            active_companies = repo.get_active()

            if not active_companies:
                print("No active companies found")
            else:
                for company in active_companies:
                    print(f"{company.name} - Created: {company.created_at}")
            ```
        """
        # Query active companies, ordered alphabetically
        records = self.select(
            filters={"is_active": True},
            order_by="name",
            ascending=True,
        )

        # Convert to domain models
        companies = [Company(**record) for record in records]

        return companies

    def get_all(self) -> list[Company]:
        """
        Get all companies (active and inactive) ordered by name.

        Returns:
            List of all Company instances (empty list if none exist)

        Raises:
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = CompaniesRepository(client)
            all_companies = repo.get_all()

            if not all_companies:
                print("No companies found")
            else:
                for company in all_companies:
                    status = "active" if company.is_active else "inactive"
                    print(f"{company.name} - {status}")
            ```
        """
        # Query all companies, ordered alphabetically
        records = self.select(
            order_by="name",
            ascending=True,
        )

        # Convert to domain models
        companies = [Company(**record) for record in records]

        return companies

    def deactivate(self, company_id: int) -> Company:
        """
        Deactivate a company (soft delete).

        Sets is_active=False and updates the updated_at timestamp.

        Args:
            company_id: ID of the company to deactivate

        Returns:
            Updated Company instance with is_active=False

        Raises:
            SupabaseNotFoundError: If company with given ID doesn't exist
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = CompaniesRepository(client)
            deactivated = repo.deactivate(company_id=5)
            assert deactivated.is_active is False
            ```
        """
        # Update is_active and updated_at
        result = self.update(
            data={
                "is_active": False,
                "updated_at": datetime.now(UTC).isoformat(),
            },
            filters={"id": company_id},
        )

        # Handle response - check if company was found
        if not result or (isinstance(result, list) and len(result) == 0):
            raise SupabaseNotFoundError(
                f"Company with ID {company_id} not found or already deactivated"
            )

        data = result[0] if isinstance(result, list) else result
        company = Company(**data)

        return company

    def activate(self, company_id: int) -> Company:
        """
        Activate a company (or reactivate an inactive one).

        Sets is_active=True and updates the updated_at timestamp.

        Args:
            company_id: ID of the company to activate

        Returns:
            Updated Company instance with is_active=True

        Raises:
            SupabaseNotFoundError: If company with given ID doesn't exist
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = CompaniesRepository(client)
            activated = repo.activate(company_id=5)
            assert activated.is_active is True
            ```
        """
        # Update is_active and updated_at
        result = self.update(
            data={
                "is_active": True,
                "updated_at": datetime.now(UTC).isoformat(),
            },
            filters={"id": company_id},
        )

        # Handle response - check if company was found
        if not result or (isinstance(result, list) and len(result) == 0):
            raise SupabaseNotFoundError(f"Company with ID {company_id} not found")

        data = result[0] if isinstance(result, list) else result
        company = Company(**data)

        return company
