"""
Job Technologies repository for managing job-technology relationship records.

Provides type-safe CRUD operations for the job_technologies table with domain model integration.
"""

from supabase import Client

from data.supebase.base_repository import BaseRepository
from data.supebase.models.job_technology import JobTechnology


class JobTechnologiesRepository(BaseRepository):
    """
    Repository for job_technologies table operations.

    Provides methods to:
    - Create new job technology association

    All methods return type-safe JobTechnology domain models.
    """

    def __init__(self, client: Client) -> None:
        """
        Initialize job technologies repository.

        Args:
            client: Supabase client instance
        """
        super().__init__(client, "job_technologies")

    def create(self, job_id: int, technology_id: int) -> JobTechnology:
        """
        Create a new job technology association.

        Args:
            job_id: ID of the job to associate
            technology_id: ID of the technology to associate

        Returns:
            Created JobTechnology instance with all fields populated

        Raises:
            SupabaseConflictError: If job-technology association already exists
            SupabaseValidationError: If job_id or technology_id are invalid
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = JobTechnologiesRepository(client)
            job_tech = repo.create(job_id=10, technology_id=5)
            print(job_tech.id)  # Auto-generated ID
            print(job_tech.job_id)  # 10
            print(job_tech.technology_id)  # 5
            ```
        """
        # Insert record (timestamps auto-generated by DB)
        result = self.insert({"job_id": job_id, "technology_id": technology_id})

        # Handle response - insert returns list or single dict
        data = result[0] if isinstance(result, list) else result

        # Convert to domain model
        job_technology = JobTechnology(**data)

        return job_technology
