"""
Technology Aliases repository for managing technology alias records.

Provides type-safe CRUD operations for the technology_aliases table with domain model integration.
"""

from supabase import Client

from data.supebase.base_repository import BaseRepository
from data.supebase.models.technology_alias import TechnologyAlias


class TechnologyAliasesRepository(BaseRepository):
    """
    Repository for technology_aliases table operations.

    Provides methods to:
    - Create new technology alias

    All methods return type-safe TechnologyAlias domain models.
    """

    def __init__(self, client: Client) -> None:
        """
        Initialize technology aliases repository.

        Args:
            client: Supabase client instance
        """
        super().__init__(client, "technology_aliases")

    def create(self, technology_id: int, alias: str) -> TechnologyAlias:
        """
        Create a new technology alias.

        Args:
            technology_id: ID of the technology this alias refers to
            alias: Alias name (must be unique, validated by DB constraint)

        Returns:
            Created TechnologyAlias instance with all fields populated

        Raises:
            SupabaseConflictError: If alias already exists
            SupabaseValidationError: If alias violates database constraints or technology_id is invalid
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = TechnologyAliasesRepository(client)
            alias = repo.create(technology_id=5, alias="py")
            print(alias.id)  # Auto-generated ID
            print(alias.alias)  # "py"
            ```
        """
        # Insert record (timestamps auto-generated by DB)
        result = self.insert({"technology_id": technology_id, "alias": alias})

        # Handle response - insert returns list or single dict
        data = result[0] if isinstance(result, list) else result

        # Convert to domain model
        technology_alias = TechnologyAlias(**data)

        return technology_alias
