"""
Technologies repository for managing technology records.

Provides type-safe CRUD operations for the technologies table with domain model integration.
"""

from supabase import Client

from data.supebase.base_repository import BaseRepository
from data.supebase.exceptions import SupabaseNotFoundError
from data.supebase.models.technology import Technology


class TechnologiesRepository(BaseRepository):
    """
    Repository for technologies table operations.

    Provides methods to:
    - Create new technology
    - Get technology by name
    - Update existing technology

    All methods return type-safe Technology domain models.
    """

    def __init__(self, client: Client) -> None:
        """
        Initialize technologies repository.

        Args:
            client: Supabase client instance
        """
        super().__init__(client, "technologies")

    def create(self, name: str, parent_id: int | None = None) -> Technology:
        """
        Create a new technology.

        Args:
            name: Technology name (must be unique, validated by DB constraint)
            parent_id: Optional parent technology ID

        Returns:
            Created Technology instance with all fields populated

        Raises:
            SupabaseConflictError: If technology name already exists
            SupabaseValidationError: If name violates database constraints
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = TechnologiesRepository(client)
            technology = repo.create(name="Python", parent_id=None)
            print(technology.id)  # Auto-generated ID
            print(technology.name)  # "Python"
            ```
        """
        # Insert record (timestamps auto-generated by DB)
        data: dict[str, str | int] = {"name": name}
        if parent_id is not None:
            data["parent_id"] = parent_id

        result = self.insert(data)

        # Handle response - insert returns list or single dict
        data_result = result[0] if isinstance(result, list) else result

        # Convert to domain model
        technology = Technology(**data_result)

        return technology

    def get_by_name(self, name: str) -> Technology:
        """
        Get technology by name.

        Args:
            name: Technology name to search for

        Returns:
            Technology instance matching the name

        Raises:
            SupabaseNotFoundError: If technology with given name doesn't exist
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = TechnologiesRepository(client)
            technology = repo.get_by_name(name="Python")
            print(technology.id)  # Technology ID
            ```
        """
        # Query by name
        records = self.select(filters={"name": name}, limit=1)

        # Check if technology was found
        if not records or len(records) == 0:
            raise SupabaseNotFoundError(f"Technology with name '{name}' not found")

        # Convert to domain model
        technology = Technology(**records[0])

        return technology

    def update_technology(
        self, technology_id: int, name: str | None = None, parent_id: int | None = None
    ) -> Technology:
        """
        Update existing technology.

        Args:
            technology_id: ID of the technology to update
            name: New technology name (optional)
            parent_id: New parent technology ID (optional)

        Returns:
            Updated Technology instance

        Raises:
            SupabaseNotFoundError: If technology with given ID doesn't exist
            SupabaseConflictError: If new name conflicts with existing technology
            SupabaseValidationError: If update violates database constraints
            SupabaseConnectionError: On connection/network errors

        Example:
            ```python
            repo = TechnologiesRepository(client)
            updated = repo.update(technology_id=5, name="Python 3")
            print(updated.name)  # "Python 3"
            ```
        """
        # Build update data
        update_data: dict[str, str | int] = {}
        if name is not None:
            update_data["name"] = name
        if parent_id is not None:
            update_data["parent_id"] = parent_id

        # Ensure there's something to update
        if not update_data:
            raise ValueError("At least one field (name or parent_id) must be provided")

        # Update technology
        result = self.update(data=update_data, filters={"id": technology_id})

        # Handle response - check if technology was found
        if not result or (isinstance(result, list) and len(result) == 0):
            raise SupabaseNotFoundError(f"Technology with ID {technology_id} not found")

        data = result[0] if isinstance(result, list) else result
        technology = Technology(**data)

        return technology
